services:
    Indykoning\GrumPHPPrettier\PrettierTask:
        class: \Indykoning\GrumPHPPrettier\PrettierTask
        arguments:
            - "@process_builder"
            - "@formatter.raw_process"
        tags:
            - { name: grumphp.task, task: prettier }
